name: Build CI

on: [push, pull_request]

jobs:
  
  build-linux:
    runs-on: ubuntu-18.04
    container: ubuntu:20.04
    
    strategy:
      fail-fast: false
      matrix:
        mach: [i3le, ti3le, i6le, ta6le] 

    env:
      TARGET_MACHINE: ${{ matrix.mach }}

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: apt-get update && apt-get install -y curl
      - name: Build bootfiles
        run: .github/scripts/dobootfile.sh
      - name: Build Chez
        run: .github/scripts/build.sh
      - name: Test Chez
        run: .github/scripts/test.sh

  build-macos:
    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        mach: [i3le, ti3le, i6le, ta6le] 

    env:
      TARGET_MACHINE: ${{ matrix.mach }}

    steps:
      - uses: actions/checkout@v1
      - name: Build bootfiles
        run: .github/scripts/dobootfile.sh
      - name: Build Chez
        run: .github/scripts/build.sh
      - name: Test Chez
        run: .github/scripts/test.sh
