---
name: CI
on: [push, pull_request]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        config:
          - machine: tpb
            os: ubuntu-22.04
            configure: --pb --threads --enable-libffi
            test: test-some-fast
          - machine: a6osx
            os: macos-12
          - machine: ta6osx
            os: macos-12
          - machine: i3le
            os: ubuntu-22.04
          - machine: ti3le
            os: ubuntu-22.04
          - machine: a6le
            os: ubuntu-22.04
          - machine: ta6le
            os: ubuntu-22.04
          - machine: i3nt
            os: windows-2022
            toolchain: vs
          - machine: ti3nt
            os: windows-2022
            toolchain: vs
          - machine: a6nt
            os: windows-2022
            toolchain: vs
          - machine: ta6nt
            os: windows-2022
            toolchain: vs
          - machine: ta6nt
            os: windows-2022
            toolchain: gcc
    runs-on: ${{ matrix.config.os }}
    env:
      TARGET_MACHINE: ${{ matrix.config.machine }}
      TOOLCHAIN: ${{ matrix.config.toolchain }}
      CONFIGURE_ARGS: ${{ matrix.config.configure }}
      TEST_TARGET: ${{ matrix.config.test }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - name: Configure git on Windows
        if: ${{ runner.os == 'Windows' }}
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup 32-bit Linux
        if: ${{ endsWith(matrix.config.machine, 'i3le') }}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install gcc-multilib lib32ncurses5-dev
      - name: Build Chez Scheme with Visual Studio
        if: ${{ matrix.config.toolchain == 'vs' }}
        shell: cmd
        run: build.bat ${{ matrix.config.machine }}
      - name: Build Chez Scheme
        run: .github/workflows/build.sh
